### ISSUE TITLE
extract_spectrum.py not working

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/megara-tools#2]
When running ...
_megaratools-extract_spectrum -s obsid11-Lcbimage_LCB_LR-R_HR7596__results/final_rss.fits -t obsid10-LcbStdStar_LCB_LR-R_HR7596_Box80__results/fiber_ids_float.txt -g '' -c 1 -o dum.fits_
on a 1yr-old image I get the following error:
_Traceback (most recent call last):
  File "/Users/agpaz/anaconda3/envs/megaradev/bin/megaratools-extract_spectrum", line 11, in <module>
    load_entry_point('megara-tools==0.1.1.dev3+g5e5b442', 'console_scripts', 'megaratools-extract_spectrum')()
  File "/Users/agpaz/anaconda3/envs/megaradev/lib/python3.7/site-packages/megaratools-0.1.dev28+g705b73b-py3.7.egg/megaratools/extract_spectrum.py", line 51, in main
AttributeError: 'FocalPlaneConf' object has no attribute 'conected_fibers'_
VER EL VIDEO DEL SIGUIENTE ENLACE:
https://www.loom.com/share/6dc39f552f91448c9ecf57874ea6fc43

**Comment by gildepaz** [comment]
I have noticed that this seems to be a typo in the extract_spectrum.py but I am not sure where it should be changed. For example, when I run it under a numina 0.22.2 environment (in my case this is called "megara" environment) it works fine but when I run it under a numina 0.24.dev0 environment I get that "AttributeError: 'FocalPlaneConf' object has no attribute 'conected_fibers'" error. In the latter case, if I manually copy the .py source and change "conected" (sic) by "connected" then it works. I guess the typo was introduced in the development version at some point.

**Comment by sergiopasra** [comment]
Update your copy of the code, this was fixed a while ago: 10afd9ac54e3fa53f8b8459e511f737072f2fc2d

**Comment by sergiopasra** [comment]
We must create a new release...

**Comment by gildepaz** [comment]
I did update everything (numina, megaradrp & megaratools) and I still get the error. Perhaps I should do a "git push" of the megaratools myself in the meantime. Would that work?

**Comment by sergiopasra** [comment]
I have just released megara-tools 0.1.1. Check that you have this version installed
